title: Liansheng Peng's Homepage
page-top-title: Liansheng Peng
top-section-bg-text: Welcome!
home-subtitle: Liansheng Peng&ensp;|&ensp;彭连胜
copyright-text: '&copy; Liansheng Peng 2025. All Rights Reserved.'
